"""
agent/pdf_export.py
PDF Export - Extension: PDF export of infrastructure planning report.
Uses fpdf2 (pure Python, no LaTeX required).
"""

from __future__ import annotations

import io
import textwrap
from datetime import datetime
from typing import Optional

try:
    from fpdf import FPDF, XPos, YPos
except ImportError:
    raise ImportError("Run: pip install fpdf2")

from agent.planning_agent import PlanningReport


# ── Colour palette ────────────────────────────────────────────────────
NAVY   = (30,  60, 114)
BLUE   = (42,  82, 152)
WHITE  = (255, 255, 255)
LIGHT  = (240, 245, 255)
DARK   = (30,  30,  40)
GRAY   = (120, 120, 120)
GREEN  = (34, 139, 34)
AMBER  = (204, 102, 0)
RED_C  = (180, 30,  30)


class ChargeWisePDF(FPDF):
    """Custom FPDF subclass with header/footer branding."""

    def __init__(self, zone_ids: list[int]):
        super().__init__()
        self.zone_ids = zone_ids
        self.set_auto_page_break(auto=True, margin=20)

    def header(self):
        # Background bar
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 16, style="F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*WHITE)
        self.set_xy(10, 3)
        self.cell(0, 10, "ChargeWise AI - EV Infrastructure Planning Report", align="L")
        self.ln(14)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*GRAY)
        self.cell(
            0, 8,
            f"Generated by ChargeWise AI  |  {datetime.now().strftime('%Y-%m-%d %H:%M')}  |  Page {self.page_no()}",
            align="C",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT
        )

    # ── Helpers ─────────────────────────────────────────────────────

    def _clean_text(self, text: str) -> str:
        """Replace common unsupported unicode characters with ASCII equivalents."""
        replacements = {
            "\u2013": "-",  # en-dash
            "\u2014": "-",  # em-dash
            "\u2018": "'",  # left single quote
            "\u2019": "'",  # right single quote
            "\u201c": '"',  # left double quote
            "\u201d": '"',  # right double quote
            "\u2022": "*",  # bullet
            "\u26a1": "EV", # bolt emoji
        }
        for old, new in replacements.items():
            text = text.replace(old, new)
        return text

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*NAVY)
        self.ln(3)
        self.cell(0, 10, self._clean_text(title), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_draw_color(*NAVY)
        self.line(self.get_x(), self.get_y(), self.get_x() + 40, self.get_y())
        self.ln(2)

    def body_text(self, text: str, color: tuple = DARK):
        self.set_x(self.l_margin)
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*color)
        self.multi_cell(0, 6, self._clean_text(text))
        self.ln(2)

    def bullet_list(self, items: list[str], icon: str = "-", color: tuple = DARK):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*color)
        for item in items:
            self.set_x(self.l_margin)
            prefix = f"{icon} "
            self.multi_cell(0, 6, self._clean_text(prefix + item))
        self.ln(1)

    def confidence_badge(self, confidence: str):
        colors = {"high": GREEN, "medium": AMBER, "low": RED_C}
        c = colors.get(confidence.lower(), GRAY)
        self.set_fill_color(*c)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 9)
        label = f"  Confidence: {confidence.upper()}  "
        self.cell(len(label) * 2.2, 7, label, fill=True, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(8)

    def key_value_row(self, key: str, value: str):
        self.set_fill_color(*LIGHT)
        self.set_text_color(*DARK)
        self.set_font("Helvetica", "B", 9)
        self.cell(60, 7, f"  {key}", fill=True, border=0)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 7, f"  {value}", fill=True, border=0,
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(1)


def generate_pdf(
    report: PlanningReport,
    zone_ids: list[int],
    stats_dict: Optional[dict] = None,
) -> bytes:
    """
    Generate a PDF planning report and return raw bytes.

    Parameters
    ----------
    report    : PlanningReport Pydantic model
    zone_ids  : list of zone TAZIDs
    stats_dict: optional flat dict of demand statistics for the metadata table
    """
    pdf = ChargeWisePDF(zone_ids=zone_ids)
    pdf.add_page()

    # ── Cover info ─────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*NAVY)
    pdf.cell(0, 10, "EV Infrastructure Planning Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*GRAY)
    pdf.cell(0, 7, f"Zone(s): {', '.join(str(z) for z in zone_ids)}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 7, f"Generated: {datetime.now().strftime('%A, %B %d, %Y at %H:%M')}",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # Confidence badge
    pdf.confidence_badge(report.confidence)

    # ── Demand statistics metadata ─────────────────────────────────
    if stats_dict:
        pdf.section_title("Demand Statistics")
        for k, v in stats_dict.items():
            pdf.key_value_row(k, str(v))
        pdf.ln(2)

    # ── Data warnings ──────────────────────────────────────────────
    if report.data_warnings:
        pdf.section_title("Data Quality Warnings")
        pdf.bullet_list(report.data_warnings, icon="!", color=AMBER)

    # ── 1. Demand Summary ──────────────────────────────────────────
    pdf.section_title("1. Charging Demand Summary")
    pdf.body_text(report.demand_summary)

    # ── 2. High-Load Locations ─────────────────────────────────────
    pdf.section_title("2. High-Load Locations")
    if report.high_load_locations:
        pdf.bullet_list(report.high_load_locations, icon="*")
    else:
        pdf.body_text("No high-load zones identified in the selected area.", color=GRAY)

    # ── 3. Infrastructure Expansion Recommendations ────────────────
    pdf.section_title("3. Infrastructure Expansion Recommendations")
    pdf.bullet_list(report.expansion_recommendations, icon="*")

    # ── 4. Scheduling & Load-Balancing Insights ────────────────────
    pdf.section_title("4. Scheduling & Load-Balancing Insights")
    pdf.bullet_list(report.scheduling_insights, icon="*")

    # ── 5. Supporting References ───────────────────────────────────
    pdf.section_title("5. Supporting References")
    pdf.body_text(
        "The following guidelines from the ChargeWise Infrastructure Planning Knowledge Base "
        "were used to validate the recommendations in this report.",
        color=GRAY
    )
    pdf.bullet_list(report.references, icon="-", color=BLUE)

    # ── Disclaimer ─────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*GRAY)
    pdf.multi_cell(
        0, 5,
        "Disclaimer: This report is generated by an AI assistant using historical charging data "
        "and publicly available infrastructure guidelines. Recommendations should be validated "
        "by qualified electrical engineers and utilities before implementation.",
    )

    return bytes(pdf.output())


# ── Smoke test ───────────────────────────────────────────────────────
if __name__ == "__main__":
    from agent.planning_agent import PlanningReport

    dummy = PlanningReport(
        demand_summary="Zone 108 recorded 45,230 kWh total with an average hourly demand of 10.4 kWh. Peak demand occurs on Tuesdays at 19:00.",
        high_load_locations=["Zone 108: top 25% by total volume with consistent evening peaks."],
        expansion_recommendations=[
            "Install 2 additional DC fast chargers (150 kW) to address evening peak (19:00–21:00).",
            "Upgrade distribution transformer to 500 kVA capacity.",
            "Deploy battery energy storage (200 kWh) to reduce peak grid demand charges.",
        ],
        scheduling_insights=[
            "Implement time-of-use pricing: peak rate 17:00–21:00, off-peak 23:00–06:00.",
            "Enable OCPP 2.0.1 smart charging for automated demand response.",
        ],
        references=[
            "IEA Global EV Outlook 2023",
            "NEVI Formula Program Standards - U.S. DOE",
            "ISO 15118: Vehicle to Grid Communication Interface",
        ],
        confidence="high",
    )

    pdf_bytes = generate_pdf(dummy, zone_ids=[108], stats_dict={
        "Total Energy": "45,230 kWh",
        "Avg Hourly Demand": "10.4 kWh",
        "Peak Hour": "19:00",
        "Peak Day": "Tuesday",
    })

    with open("/tmp/test_report.pdf", "wb") as f:
        f.write(pdf_bytes)
    print("PDF written to /tmp/test_report.pdf")
